### ISSUE TITLE
Bixby impossible to lock 

### ISSUE THREAD

**Issue by Corentinfaye** [TheLastMillennial/fencing-buzzer#4]
Hey man,

thank you for your application and your work. I use your app actually but I have an issue when the top slider must block all the buttion Bixby continues to respond and block the app fencing-buzzer.
I have tried to deactivate all Bibxy but it's impossible so i don't how if it's must be a feature to add to the application or it must be a work on my side.

Have a good day.

**Comment by TheLastMillennial** [comment]
Unfortunately it doesn't seem like there's much I can do on my end. I don't think apps have the ability to disable Bixby. However there are steps you can try to disable Bixby. Try method 4 in the following link which involves installing a different home screen (personally I use the Microsoft launcher or Evie). It's not permanent so you can go back to the original home screen if it doesn't work.
https://android.gadgethacks.com/how-to/completely-disable-bixby-your-samsung-galaxy-0187578/

**Comment by Corentinfaye** [comment]
Thank you very much for your answer. I'm gonna try this possibility. 

Just another question : do you continue to improve the application to create the possibility to link two smartphone and to have a touching machine

**Comment by TheLastMillennial** [comment]
Let me know if it works out for you!

Yes, I'm still working on a way to get the latency down enough that this project could be reliably used in practice. However, this project isn't on my priority list right now so it may be a while before I can implement my next idea.

**Comment by TheLastMillennial** [comment]
I'm going to assume a week of silence means it's been working.
